# parameter for the reference speed
pub_ref_spd:
  ros__parameters:
    ref_spd: 0.0

# control by joystick or automatically
rover_odometry_node:
  ros__parameters:
    wheelbase: 0.55
    update_frequency: 20.0
    is_radio: 0

# decide whether to use angle steering correction and throttle speed PI control
low_level_control_easy_play:
  ros__parameters:
    is_steering_correction: 1
    is_throttle_correction: 0
    distance_travel: 5.0

# OBPS recevier parameters, port need to be adjusted
obps_receiver:
  ros__parameters:
    obps_port: 9999
    buffer_size: 2048

# tactical node parameters definition
tactical_node:
  ros__parameters:
    cr_point_1: [2.0, 2.0]
    cr_point_2: [2.0, -2.0]
    cr_point_3: [-2.0, -2.0]
    cr_point_4: [-2.0, 2.0]
    adv_path_start: [0.0, -4.0]
    adv_path_end: [0.0, 2.0]
    ego_path_start: [4.0, 0.0]
    ego_path_end: [-2.0, 0.0]
    ego_ref_speed: 1.5
    adv_max_speed: 1.25
    ego_max_acc: 1.35
    ego_max_dec: 1.25
    adv_max_acc: 1.05
    ego_length: 0.720
    ego_width: 0.515
    adv_length: 0.720
    adv_width: 0.515
    use_start_socket: true
    start_socket_host: '0.0.0.0'
    start_socket_port: 9000