# parameter for the reference speed
pub_ref_spd:
  ros__parameters:
    ref_spd: 1.0

# control by joystick or automatically
rover_odometry_node:
  ros__parameters:
    wheelbase: 0.55
    update_frequency: 20.0
    is_radio: 0

# decide whether to use angle steering correction and throttle speed PI control
low_level_control_easy_play:
  ros__parameters:
    is_steering_correction: 0
    is_throttle_correction: 0
    distance_travel: 5.0
